[pr_implement]
allow_agent_implementation=true

[config]
new_diff_format=true
new_diff_format_line_numbers=true
new_diff_format_add_external_references=true


[best_practices]
enable_global_best_practices = true
organization_name="Qodo"

[linear]
linear_base_url = "https://linear.app/qodo"

[github_app]
pr_commands = [
    "/describe --pr_description.final_update_message=false",
    "/compliance",
    "/improve",
    "/agentic_review"  # experimental, avert production for now.
]

handle_push_trigger = true
push_commands = [
    "/describe",
    "/compliance --update_compliance=true",
    "/improve"
]

[review_agent]
enabled = true
publish_output = true
enable_issues_agent = true
enable_compliance_agent = true
judge_enabled = true


